### ISSUE TITLE
VPO-MSMI Release

### ISSUE THREAD

**Issue by denfed** [cyh-0/CAVP#1]
Hello, can you release the multi source dataset you created? Thank you!

**Comment by denfed** [comment]
Specifically, I noticed the position information is missing from the CSV's provided in the dataset.

**Comment by cyh-0** [comment]
Hi denfed,

I have update the drive and here is the file path [https://drive.google.com/file/d/12jq7-Ke09ZPoUI1od44q97DNLrThoHc3/view?usp=sharing](url)

Cheers

**Comment by denfed** [comment]
Thank you!

**Comment by itruonghai** [comment]
Hi @cyh-0,

Could you please double-check the vpo_msmi_data_stereo.csv file? It seems to be identical to vpo_ms_data_stereo.csv

**Comment by cyh-0** [comment]
Hi @itruonghai,

The msmi.csv file is an extension of ms.csv, so there are some overlaps between them. However, these two files are not identical.

Cheers,
Yuanhong
