### ISSUE TITLE
I'm curious about your balancing  process in paper?

### ISSUE THREAD

**Issue by ButlerZOH** [cyh-0/CAVP#4]
Please refer to the Supplementary Material for details on the balancing process. where is it?

**Comment by cyh-0** [comment]
The balancing process is related to the https://github.com/cyh-0/CAVP/blob/b468a819ff20f9976d8e14a2a230338b750dbd8e/trainer/trainer_cavp_vpo_mono.py#L156, which remove part of the negative pairs to form positive pairs.
