### ISSUE TITLE
Question about weight file of ckpt

### ISSUE THREAD

**Issue by c1ircle** [cyh-0/CAVP#7]
Thank you for your excellent work. I encountered a weight file mismatch issue during the training process and I am using the official ResNet50 weight file. Could you please provide the visual backbone and VGG weight files you used in your code? Thank you.
![image](https://github.com/user-attachments/assets/18918563-1dea-41ba-aba4-e42ea98217e6)

**Comment by cyh-0** [comment]
Here are the resnet50's [checkpoint](https://drive.google.com/file/d/1A4u-BQTwBvm1cprN6ehl-tlEI-d0ZoL9/view?usp=drive_link) and VGG's [checkpoint](https://drive.google.com/file/d/1JfkZ2NE8fsVwykSGRrG2vo5w7BGP02zm/view?usp=drive_link)
